feat: 1월 첫째주 목표
Road-of-CODEr/stupid-week-2021 pull request #6
Opened 2021-01-04 14:27 UTC by soobing

## 완료된 목표 3가지를 적어주세요

1. 
2. 
3. 

## 다음주 목표 3가지를 적어주세요

1. leet code 두 문제 
  - [중복 문자 제거](https://leetcode.com/problems/remove-duplicate-letters/)
  - [k개 정렬 리스트 병합](
https://leetcode.com/problems/merge-k-sorted-lists/)
2. hooks 딥다이브
3. next.js 토이프로젝트 main 페이지 개발

2021-01-09 15:29 UTC, huisam approved these changes
안녕하세요 ㅎㅎ 반갑습니다.! 새로운 한해도 화이팅이에요! 🥇

2021-01-10 14:58 UTC, juheekimm approved these changes
안녕하세요 반갑습니다 😄 😄  함께하게 되어서 기뻐요!ㅎㅎ
이번 한주도 고생하셨습니다!

2021-01-10 15:33 UTC, 1ilsang requested changes
고생하셨습니다

2021-01-10 15:33 UTC, 1ilsang commented on 2021/01/10/soobing/README.md
> +https://leetcode.com/problems/merge-k-sorted-lists/)
요기 링크가 깨진거 같은데욥?

2021-01-11 07:07 UTC, soobing commented on 2021/01/10/soobing/README.md
> +https://leetcode.com/problems/merge-k-sorted-lists/)
수정했습니다 ㅎㅎ 꼼꼼하게 봐주셨네용 🙇🏻‍♀️

2021-01-11 16:23 UTC, 1ilsang approved these changes

2021-01-11 16:23 UTC, merged