feat(parkinhyo): ~1/10 목표 작성
Road-of-CODEr/stupid-week-2021 pull request #7
Opened 2021-01-04 15:20 UTC by PARKINHYO

## 완료된 목표 3가지를 적어주세요

1. 
2. 
3. 

## 다음주 목표 3가지를 적어주세요

1. 파이썬 알고리즘 인터뷰 13장 최단 경로, 14장 트리
2. 코로나 알림 카카오 채널 토이 프로젝트 조금씩
3. 오픽 자기소개, 집, 동네, 공원 예상 질문 스크립트 제작, 암기

2021-01-09 15:28 UTC, huisam approved these changes
새로운 한해도 화이팅입니다!! ㅎㅎ 🥇

2021-01-10 15:00 UTC, juheekimm approved these changes

2021-01-10 15:00 UTC, juheekimm commented on 2021/01/10/parkinhyo/README.md
> +2. 코로나 알림 카카오 채널 토이 프로젝트 조금씩
와우! 기대되네요 ㅎㅎ 꾸준히 도전하시는 모습 멋져요 👍 
올 한해도 화이팅입니다!ㅎㅎ

2021-01-10 15:32 UTC, 1ilsang requested changes
다음주 목표면 10일차가 아닌 17일차 readme 로 올려주셔야 합니다~

수정 부탁드려요!

2021-01-11 04:15 UTC, PARKINHYO commented on 2021/01/10/parkinhyo/README.md
> +2. 코로나 알림 카카오 채널 토이 프로젝트 조금씩
감사합니다..!!

2021-01-11 04:19 UTC, PARKINHYO commented
> 새로운 한해도 화이팅입니다!! ㅎㅎ 🥇

@huisam 님도 적게 일하고 많이 버세요 ㅎㅎ

2021-01-11 04:24 UTC, PARKINHYO commented
> 새로운 한해도 화이팅입니다!! ㅎㅎ 🥇

@huisam 님도 화이팅이요..!!!

2021-01-11 04:35 UTC, PARKINHYO commented
> 다음주 목표면 10일차가 아닌 17일차 readme 로 올려주셔야 합니다~
> 
> 수정 부탁드려요!

저번주 목표가 맞습니다 ㅎㅎ 완료 링크 올렸습니다..!! 17일차 readme도 올렸습니당

2021-01-11 16:24 UTC, 1ilsang approved these changes

2021-01-11 16:24 UTC, merged